//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.UsuarioTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/LocalizaV1.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioTest.IUsuarioSVC")]
    public interface IUsuarioSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSVC/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioSVC/CrearUsuarioResponse")]
        TestProject1.UsuarioTest.Usuario CrearUsuario(string nombre, string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSVC/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioSVC/ObtenerUsuarioResponse")]
        TestProject1.UsuarioTest.Usuario ObtenerUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSVC/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarioSVC/ModificarUsuarioResponse")]
        TestProject1.UsuarioTest.Usuario ModificarUsuario(int codigo, string nombre, string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSVC/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioSVC/EliminarUsuarioResponse")]
        void EliminarUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSVC/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarioSVC/ListarUsuariosResponse")]
        TestProject1.UsuarioTest.Usuario[] ListarUsuarios();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioSVCChannel : TestProject1.UsuarioTest.IUsuarioSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioSVCClient : System.ServiceModel.ClientBase<TestProject1.UsuarioTest.IUsuarioSVC>, TestProject1.UsuarioTest.IUsuarioSVC {
        
        public UsuarioSVCClient() {
        }
        
        public UsuarioSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestProject1.UsuarioTest.Usuario CrearUsuario(string nombre, string correo, string password) {
            return base.Channel.CrearUsuario(nombre, correo, password);
        }
        
        public TestProject1.UsuarioTest.Usuario ObtenerUsuario(int codigo) {
            return base.Channel.ObtenerUsuario(codigo);
        }
        
        public TestProject1.UsuarioTest.Usuario ModificarUsuario(int codigo, string nombre, string correo, string password) {
            return base.Channel.ModificarUsuario(codigo, nombre, correo, password);
        }
        
        public void EliminarUsuario(int codigo) {
            base.Channel.EliminarUsuario(codigo);
        }
        
        public TestProject1.UsuarioTest.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
    }
}
