//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLocaliza.UbicacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubicacion", Namespace="http://schemas.datacontract.org/2004/07/LocalizaV1.Dominio")]
    [System.SerializableAttribute()]
    public partial class Ubicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idEnvio {
            get {
                return this.idEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.idEnvioField, value) != true)) {
                    this.idEnvioField = value;
                    this.RaisePropertyChanged("idEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitud {
            get {
                return this.latitudField;
            }
            set {
                if ((this.latitudField.Equals(value) != true)) {
                    this.latitudField = value;
                    this.RaisePropertyChanged("latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UbicacionService.IUbicacionService")]
    public interface IUbicacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionService/actualizaUbicacion", ReplyAction="http://tempuri.org/IUbicacionService/actualizaUbicacionResponse")]
        string actualizaUbicacion(WebLocaliza.UbicacionService.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionService/listaUbicacion", ReplyAction="http://tempuri.org/IUbicacionService/listaUbicacionResponse")]
        WebLocaliza.UbicacionService.Ubicacion listaUbicacion(string idenvio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUbicacionServiceChannel : WebLocaliza.UbicacionService.IUbicacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UbicacionServiceClient : System.ServiceModel.ClientBase<WebLocaliza.UbicacionService.IUbicacionService>, WebLocaliza.UbicacionService.IUbicacionService {
        
        public UbicacionServiceClient() {
        }
        
        public UbicacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UbicacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbicacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbicacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string actualizaUbicacion(WebLocaliza.UbicacionService.Ubicacion ubicacion) {
            return base.Channel.actualizaUbicacion(ubicacion);
        }
        
        public WebLocaliza.UbicacionService.Ubicacion listaUbicacion(string idenvio) {
            return base.Channel.listaUbicacion(idenvio);
        }
    }
}
