'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EnviosService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Envio", [Namespace]:="http://schemas.datacontract.org/2004/07/REST.Dominio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Envio
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CantidadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinoFinField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestinoInicioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdEnvioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTransporteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PesoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cantidad() As String
            Get
                Return Me.CantidadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CantidadField, value) <> true) Then
                    Me.CantidadField = value
                    Me.RaisePropertyChanged("Cantidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DestinoFin() As String
            Get
                Return Me.DestinoFinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinoFinField, value) <> true) Then
                    Me.DestinoFinField = value
                    Me.RaisePropertyChanged("DestinoFin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DestinoInicio() As String
            Get
                Return Me.DestinoInicioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestinoInicioField, value) <> true) Then
                    Me.DestinoInicioField = value
                    Me.RaisePropertyChanged("DestinoInicio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCliente() As String
            Get
                Return Me.IdClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdClienteField, value) <> true) Then
                    Me.IdClienteField = value
                    Me.RaisePropertyChanged("IdCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdEnvio() As String
            Get
                Return Me.IdEnvioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdEnvioField, value) <> true) Then
                    Me.IdEnvioField = value
                    Me.RaisePropertyChanged("IdEnvio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTransporte() As String
            Get
                Return Me.IdTransporteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdTransporteField, value) <> true) Then
                    Me.IdTransporteField = value
                    Me.RaisePropertyChanged("IdTransporte")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Peso() As String
            Get
                Return Me.PesoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PesoField, value) <> true) Then
                    Me.PesoField = value
                    Me.RaisePropertyChanged("Peso")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EnviosService.IEnviosSVC")>  _
    Public Interface IEnviosSVC
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEnviosSVC/CrearEnvio", ReplyAction:="http://tempuri.org/IEnviosSVC/CrearEnvioResponse")>  _
        Function CrearEnvio(ByVal envioACrear As EnviosService.Envio) As EnviosService.Envio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEnviosSVC/ObtenerEnvio", ReplyAction:="http://tempuri.org/IEnviosSVC/ObtenerEnvioResponse")>  _
        Function ObtenerEnvio(ByVal idEnvio As String) As EnviosService.Envio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEnviosSVC/EliminarEnvio", ReplyAction:="http://tempuri.org/IEnviosSVC/EliminarEnvioResponse")>  _
        Function EliminarEnvio(ByVal idEnvio As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEnviosSVC/ListarEnvios", ReplyAction:="http://tempuri.org/IEnviosSVC/ListarEnviosResponse")>  _
        Function ListarEnvios() As EnviosService.Envio()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEnviosSVCChannel
        Inherits EnviosService.IEnviosSVC, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EnviosSVCClient
        Inherits System.ServiceModel.ClientBase(Of EnviosService.IEnviosSVC)
        Implements EnviosService.IEnviosSVC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CrearEnvio(ByVal envioACrear As EnviosService.Envio) As EnviosService.Envio Implements EnviosService.IEnviosSVC.CrearEnvio
            Return MyBase.Channel.CrearEnvio(envioACrear)
        End Function
        
        Public Function ObtenerEnvio(ByVal idEnvio As String) As EnviosService.Envio Implements EnviosService.IEnviosSVC.ObtenerEnvio
            Return MyBase.Channel.ObtenerEnvio(idEnvio)
        End Function
        
        Public Function EliminarEnvio(ByVal idEnvio As String) As String Implements EnviosService.IEnviosSVC.EliminarEnvio
            Return MyBase.Channel.EliminarEnvio(idEnvio)
        End Function
        
        Public Function ListarEnvios() As EnviosService.Envio() Implements EnviosService.IEnviosSVC.ListarEnvios
            Return MyBase.Channel.ListarEnvios
        End Function
    End Class
End Namespace
