'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceCliente
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/LocalizaV1.Dominio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private apMaternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private apPaternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private direccionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private distritoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dniField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private emailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private generoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private telefonoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property apMaterno() As String
            Get
                Return Me.apMaternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.apMaternoField, value) <> true) Then
                    Me.apMaternoField = value
                    Me.RaisePropertyChanged("apMaterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property apPaterno() As String
            Get
                Return Me.apPaternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.apPaternoField, value) <> true) Then
                    Me.apPaternoField = value
                    Me.RaisePropertyChanged("apPaterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.direccionField, value) <> true) Then
                    Me.direccionField = value
                    Me.RaisePropertyChanged("direccion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property distrito() As String
            Get
                Return Me.distritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.distritoField, value) <> true) Then
                    Me.distritoField = value
                    Me.RaisePropertyChanged("distrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dni() As String
            Get
                Return Me.dniField
            End Get
            Set
                If (Object.ReferenceEquals(Me.dniField, value) <> true) Then
                    Me.dniField = value
                    Me.RaisePropertyChanged("dni")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.emailField, value) <> true) Then
                    Me.emailField = value
                    Me.RaisePropertyChanged("email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property genero() As String
            Get
                Return Me.generoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.generoField, value) <> true) Then
                    Me.generoField = value
                    Me.RaisePropertyChanged("genero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idCliente() As Integer
            Get
                Return Me.idClienteField
            End Get
            Set
                If (Me.idClienteField.Equals(value) <> true) Then
                    Me.idClienteField = value
                    Me.RaisePropertyChanged("idCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreField, value) <> true) Then
                    Me.nombreField = value
                    Me.RaisePropertyChanged("nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.telefonoField, value) <> true) Then
                    Me.telefonoField = value
                    Me.RaisePropertyChanged("telefono")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceCliente.IClienteSVC")>  _
    Public Interface IClienteSVC
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/CrearCliente", ReplyAction:="http://tempuri.org/IClienteSVC/CrearClienteResponse")>  _
        Function CrearCliente(ByVal nombre As String, ByVal paterno As String, ByVal materno As String, ByVal genero As String, ByVal dni As String, ByVal email As String, ByVal telefono As String, ByVal direccion As String, ByVal distrito As String) As ServiceCliente.Cliente
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/ObtenerCliente", ReplyAction:="http://tempuri.org/IClienteSVC/ObtenerClienteResponse")>  _
        Function ObtenerCliente(ByVal codigo As Integer) As ServiceCliente.Cliente
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/ModificarCliente", ReplyAction:="http://tempuri.org/IClienteSVC/ModificarClienteResponse")>  _
        Function ModificarCliente(ByVal codigo As Integer, ByVal nombre As String, ByVal paterno As String, ByVal materno As String, ByVal genero As String, ByVal dni As String, ByVal email As String, ByVal telefono As String, ByVal direccion As String, ByVal distrito As String) As ServiceCliente.Cliente
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/EliminarCliente", ReplyAction:="http://tempuri.org/IClienteSVC/EliminarClienteResponse")>  _
        Sub EliminarCliente(ByVal codigo As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/ListarCliente", ReplyAction:="http://tempuri.org/IClienteSVC/ListarClienteResponse")>  _
        Function ListarCliente() As ServiceCliente.Cliente()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/validaDni", ReplyAction:="http://tempuri.org/IClienteSVC/validaDniResponse")>  _
        Function validaDni(ByVal dni As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteSVC/mensajes", ReplyAction:="http://tempuri.org/IClienteSVC/mensajesResponse")>  _
        Function mensajes(ByVal valor As Integer) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IClienteSVCChannel
        Inherits ServiceCliente.IClienteSVC, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClienteSVCClient
        Inherits System.ServiceModel.ClientBase(Of ServiceCliente.IClienteSVC)
        Implements ServiceCliente.IClienteSVC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CrearCliente(ByVal nombre As String, ByVal paterno As String, ByVal materno As String, ByVal genero As String, ByVal dni As String, ByVal email As String, ByVal telefono As String, ByVal direccion As String, ByVal distrito As String) As ServiceCliente.Cliente Implements ServiceCliente.IClienteSVC.CrearCliente
            Return MyBase.Channel.CrearCliente(nombre, paterno, materno, genero, dni, email, telefono, direccion, distrito)
        End Function
        
        Public Function ObtenerCliente(ByVal codigo As Integer) As ServiceCliente.Cliente Implements ServiceCliente.IClienteSVC.ObtenerCliente
            Return MyBase.Channel.ObtenerCliente(codigo)
        End Function
        
        Public Function ModificarCliente(ByVal codigo As Integer, ByVal nombre As String, ByVal paterno As String, ByVal materno As String, ByVal genero As String, ByVal dni As String, ByVal email As String, ByVal telefono As String, ByVal direccion As String, ByVal distrito As String) As ServiceCliente.Cliente Implements ServiceCliente.IClienteSVC.ModificarCliente
            Return MyBase.Channel.ModificarCliente(codigo, nombre, paterno, materno, genero, dni, email, telefono, direccion, distrito)
        End Function
        
        Public Sub EliminarCliente(ByVal codigo As Integer) Implements ServiceCliente.IClienteSVC.EliminarCliente
            MyBase.Channel.EliminarCliente(codigo)
        End Sub
        
        Public Function ListarCliente() As ServiceCliente.Cliente() Implements ServiceCliente.IClienteSVC.ListarCliente
            Return MyBase.Channel.ListarCliente
        End Function
        
        Public Function validaDni(ByVal dni As String) As Boolean Implements ServiceCliente.IClienteSVC.validaDni
            Return MyBase.Channel.validaDni(dni)
        End Function
        
        Public Function mensajes(ByVal valor As Integer) As String Implements ServiceCliente.IClienteSVC.mensajes
            Return MyBase.Channel.mensajes(valor)
        End Function
    End Class
End Namespace
