//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.ContraseñaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContraseñaService.IContraseña")]
    public interface IContraseña {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContraseña/CambContraseña", ReplyAction="http://tempuri.org/IContraseña/CambContraseñaResponse")]
        string CambContraseña(string usuario, string nuevaContraseña, string contraseña2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContraseña/ValidaContraseñaActual", ReplyAction="http://tempuri.org/IContraseña/ValidaContraseñaActualResponse")]
        string ValidaContraseñaActual(string usuario, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContraseñaChannel : TestProject1.ContraseñaService.IContraseña, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContraseñaClient : System.ServiceModel.ClientBase<TestProject1.ContraseñaService.IContraseña>, TestProject1.ContraseñaService.IContraseña {
        
        public ContraseñaClient() {
        }
        
        public ContraseñaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContraseñaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContraseñaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContraseñaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CambContraseña(string usuario, string nuevaContraseña, string contraseña2) {
            return base.Channel.CambContraseña(usuario, nuevaContraseña, contraseña2);
        }
        
        public string ValidaContraseñaActual(string usuario, string contraseña) {
            return base.Channel.ValidaContraseñaActual(usuario, contraseña);
        }
    }
}
