'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cliente

    '''<summary>
    '''C_DNI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_DNI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_Consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Consultar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''C_Nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Nombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_ApPaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_ApPaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_ApeMaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_ApeMaterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_Genero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Genero As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''C_Correo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Correo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_Telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Telefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_Distrito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Distrito As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''C_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''C_Guardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_Guardar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbltexto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltexto As Global.System.Web.UI.WebControls.Label
End Class
